services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: library-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
#      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - library-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: library-redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - library-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

#  zookeeper:
#    image: confluentinc/cp-zookeeper:7.4.0
#    container_name: library-zookeeper
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_TICK_TIME: 2000
#    ports:
#      - "2181:2181"
#    networks:
#      - library-network
#    healthcheck:
#      test: ["CMD-SHELL", "echo ruok | nc localhost 2181"]
#      interval: 10s
#      timeout: 5s
#      retries: 5

#  kafka:
#    image: confluentinc/cp-kafka:7.4.0
#    container_name: library-kafka
#    depends_on:
#      zookeeper:
#        condition: service_healthy
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_BROKER_ID: -1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:${KAFKA_HOST_PORT}
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
#      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
#      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
#      KAFKA_DELETE_TOPIC_ENABLE: "true"
#    volumes:
#      - kafka_data:/var/lib/kafka/data
#    networks:
#      - library-network
#    healthcheck:
#      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list"]
#      interval: 10s
#      timeout: 5s
#      retries: 5

  library-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: library-app
    env_file:
      - .env
    depends_on:
      postgres: { condition: service_healthy }
      redis: { condition: service_healthy }
#      kafka: { condition: service_healthy }
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/library
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD:
#      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SERVER_PORT: 8082
    #expose: ["8082"]
    expose: ["${BACKEND_PORT_INTERNAL}"]
    ports:
      #- "0.0.0.0:8082:8082"
      - "${BACKEND_PORT_EXTERNAL}:${BACKEND_PORT_INTERNAL}"
    networks: [library-network]
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:8082/api/health"]
#      interval: 30s
#      timeout: 10s
#      retries: 3
#      start_period: 60s

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: library-frontend
    depends_on:
      - library-app
    environment:
#      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8082/api/v1
      - NEXT_PUBLIC_API_BASE_URL=https://libraryfsoft.ddns.net/api/v1
      - NODE_ENV=development
    #expose: ["8081"]
    expose: ["${FRONTEND_PORT_INTERNAL}"]
    ports:
      #- "0.0.0.0:8081:8081"
      - "${FRONTEND_PORT_EXTERNAL}:${FRONTEND_PORT_INTERNAL}"
    volumes:
      - /frontend:/app
      - /app/node_modules
    networks: [library-network]

volumes:
  postgres_data:
  redis_data:
#  kafka_data:

networks:
  library-network:
    driver: bridge
